# Generated by Django 4.1.7 on 2023-06-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
