# Generated by Django 4.2.1 on 2023-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options_product_ass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ass',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
