# Generated by Django 4.2.1 on 2023-05-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_ass_alter_product_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_add',
            field=models.DateTimeField(verbose_name='Дата добавления'),
        ),
    ]
