# Generated by Django 4.2.1 on 2023-05-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
    ]
