# Generated by Django 4.1.7 on 2023-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_brand_product_gender_product_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'мужской'), ('f', 'женский')], max_length=40, verbose_name='Пол'),
        ),
    ]
