# Generated by Django 4.1.7 on 2023-06-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_thumbnail_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=40, verbose_name='Пол'),
        ),
    ]
