# Generated by Django 4.1.7 on 2023-06-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0011_alter_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя и Фамилия')),
                ('email', models.CharField(max_length=120, verbose_name='Почта')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('mobile', models.CharField(max_length=50)),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Время создания ')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплата')),
                ('paid_amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
